'use client'

import { useState } from 'react'
import { Sparkles, X } from 'lucide-react'

type Item = { summary: string; created_at: string }

function renderLine(text: string) {
  const parts = text.split(/\*\*(.*?)\*\*/g)
  return parts.map((part, i) =>
    i % 2 === 1
      ? <strong key={i} style={{ color: 'var(--artha-text)', fontWeight: 700 }}>{part}</strong>
      : <span key={i}>{part}</span>
  )
}

function parseBullets(text: string): string[] {
  return text
    .split('\n')
    .map(l => l.trim())
    .filter(l => l.startsWith('•') || l.startsWith('-') || l.match(/^\d\./))
    .map(l => l.replace(/^[•\-]\s*/, '').replace(/^\d\.\s*/, ''))
    .filter(Boolean)
}

const BULLET_LABELS = ['Theme', 'Markets', 'India']
const BULLET_ICONS  = ['🎯', '🌐', '🇮🇳']

function BriefModal({ title, brief, onClose }: { title: string; brief: string; onClose: () => void }) {
  const bullets = parseBullets(brief)
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4" onClick={onClose}>
      <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" />
      <div
        className="relative w-full max-w-md rounded-2xl shadow-2xl overflow-hidden"
        style={{ background: 'var(--artha-card)', border: '1px solid rgba(0,106,97,0.2)' }}
        onClick={e => e.stopPropagation()}
      >
        <div
          className="flex items-center justify-between px-5 py-4"
          style={{
            background: 'linear-gradient(135deg, rgba(0,61,155,0.06), rgba(0,106,97,0.08))',
            borderBottom: '1px solid rgba(0,106,97,0.12)',
          }}
        >
          <div className="flex items-center gap-2">
            <div
              className="flex items-center justify-center rounded-lg"
              style={{ width: 28, height: 28, background: 'linear-gradient(135deg, #003d9b, #006a61)' }}
            >
              <Sparkles size={13} color="white" strokeWidth={2.5} />
            </div>
            <div>
              <div className="text-xs font-bold" style={{ color: 'var(--artha-text)', letterSpacing: '-0.01em' }}>AI Brief</div>
              <div className="text-[10px]" style={{ color: 'var(--artha-text-muted)' }}>{title}</div>
            </div>
          </div>
          <button
            onClick={onClose}
            className="flex items-center justify-center rounded-full hover:bg-black/05 transition-colors"
            style={{ width: 28, height: 28, color: 'var(--artha-text-muted)' }}
          >
            <X size={15} />
          </button>
        </div>
        <div className="px-5 py-4 space-y-3">
          {bullets.length > 0 ? bullets.map((bullet, i) => (
            <div
              key={i}
              className="flex gap-3 rounded-xl px-4 py-3"
              style={{ background: 'var(--artha-surface-low)', border: '1px solid rgba(11,28,48,0.06)' }}
            >
              <div className="shrink-0 text-base leading-snug mt-0.5">{BULLET_ICONS[i] ?? '•'}</div>
              <div className="min-w-0">
                <div className="text-[10px] font-bold uppercase tracking-widest mb-1" style={{ color: 'var(--artha-teal)' }}>
                  {BULLET_LABELS[i] ?? `Point ${i + 1}`}
                </div>
                <div className="text-sm leading-relaxed" style={{ color: 'var(--artha-text-secondary)' }}>
                  {renderLine(bullet)}
                </div>
              </div>
            </div>
          )) : (
            <div className="text-sm leading-relaxed whitespace-pre-line" style={{ color: 'var(--artha-text-secondary)' }}>
              {renderLine(brief)}
            </div>
          )}
        </div>
        <div className="px-5 pb-4 text-[10px] text-center" style={{ color: 'var(--artha-text-faint)' }}>
          Generated by Noesis AI · Haiku · Not investment advice
        </div>
      </div>
    </div>
  )
}

const COOLDOWN_MS = 2 * 60 * 60 * 1000

// period is passed from parent (MacroNewsCard owns the period state)
export default function AiBriefButton({
  items,
  type,
  title,
  period,
}: {
  items: Item[]
  type: 'trump' | 'macro'
  title: string
  period: string
}) {
  const cacheKey = `noesis_brief_${type}_${period}`

  function loadCache() {
    try {
      const raw = sessionStorage.getItem(cacheKey)
      if (!raw) return null
      const data = JSON.parse(raw)
      if (Date.now() - data.ts > COOLDOWN_MS) { sessionStorage.removeItem(cacheKey); return null }
      return data
    } catch { return null }
  }

  const cached = typeof window !== 'undefined' ? loadCache() : null
  const [state, setState] = useState<'idle' | 'loading' | 'done'>(cached ? 'done' : 'idle')
  const [brief, setBrief] = useState<string | null>(cached?.brief ?? null)
  const [open, setOpen]   = useState(false)

  async function generate() {
    if (state === 'done' && brief) { setOpen(true); return }
    if (!items.length) return
    setState('loading')
    try {
      const res  = await fetch('/api/macro-brief', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ type, items }),
      })
      const json = await res.json()
      const text = json.brief ?? 'Could not generate brief.'
      try { sessionStorage.setItem(cacheKey, JSON.stringify({ brief: text, ts: Date.now() })) } catch { /* ignore */ }
      setBrief(text)
      setState('done')
      setOpen(true)
    } catch {
      setBrief('Error generating brief.')
      setState('done')
      setOpen(true)
    }
  }

  return (
    <>
      <button
        onClick={generate}
        disabled={state === 'loading' || items.length === 0}
        className="flex items-center gap-1.5 text-[10px] font-semibold px-2.5 py-1 rounded-full transition-all disabled:opacity-40"
        style={{
          background: 'linear-gradient(135deg, rgba(0,61,155,0.08), rgba(0,106,97,0.08))',
          border: '1px solid rgba(0,106,97,0.2)',
          color: 'var(--artha-teal)',
        }}
      >
        <Sparkles size={10} strokeWidth={2.5} />
        {state === 'loading' ? 'Briefing…' : 'AI Brief'}
      </button>

      {open && brief && (
        <BriefModal title={`${title} · ${period}`} brief={brief} onClose={() => setOpen(false)} />
      )}
    </>
  )
}
