// Maps granular BSE stock industry → broad FII/NSE sector name
// Used in overview page (sector exposure card) and watchlist sector correlation
export const INDUSTRY_TO_FII_SECTOR: Record<string, string> = {

  // ── Financial Services ───────────────────────────────────────────────────
  'Private Sector Bank':                          'Financial Services',
  'Public Sector Bank':                           'Financial Services',
  'Other Bank':                                   'Financial Services',
  'Non Banking Financial Company (NBFC)':         'Financial Services',
  'Finance - Term Lending Institutions':          'Financial Services',
  'Finance - Investments':                        'Financial Services',
  'Finance - Others':                             'Financial Services',
  'Finance - Housing':                            'Financial Services',
  'Finance - Leasing & Hire Purchase':            'Financial Services',
  'Life Insurance':                               'Financial Services',
  'General Insurance':                            'Financial Services',
  'Insurance':                                    'Financial Services',
  'Financial Institution':                        'Financial Services',
  'Investment Company':                           'Financial Services',
  'Wealth Management':                            'Financial Services',
  'Asset Management':                             'Financial Services',
  'Stock/ Commodity Brokers':                     'Financial Services',
  'Microfinance Institutions':                    'Financial Services',
  'Gold Financing':                               'Financial Services',
  'Exchange & Data Platform':                     'Financial Services',
  'Credit Rating':                                'Financial Services',
  'Depositories':                                 'Financial Services',

  // ── Information Technology ───────────────────────────────────────────────
  'Computers - Software & Consulting':            'Information Technology',
  'IT Enabled Services':                          'Information Technology',
  'Computer Hardware':                            'Information Technology',
  'IT - Software':                                'Information Technology',
  'IT - Hardware':                                'Information Technology',
  'Software Products':                            'Information Technology',
  'Technology Hardware & Equipment':              'Information Technology',
  'Internet & E-Commerce':                        'Information Technology',
  'Data Processing & Outsourced Services':        'Information Technology',
  'Electronic Components':                        'Information Technology',
  'Electronics':                                  'Information Technology',
  'Semiconductors':                               'Information Technology',

  // ── Oil, Gas & Consumable Fuels ──────────────────────────────────────────
  'Oil Exploration & Production':                 'Oil, Gas & Consumable Fuels',
  'Refineries & Marketing':                       'Oil, Gas & Consumable Fuels',
  'Oil & Gas':                                    'Oil, Gas & Consumable Fuels',
  'Gas Distribution':                             'Oil, Gas & Consumable Fuels',
  'Petroleum Products':                           'Oil, Gas & Consumable Fuels',
  'LNG Processing':                               'Oil, Gas & Consumable Fuels',
  'Coal':                                         'Oil, Gas & Consumable Fuels',

  // ── Automobile and Auto Components ───────────────────────────────────────
  'Passenger Cars & Utility Vehicles':            'Automobile and Auto Components',
  'Auto Components & Equipments':                 'Automobile and Auto Components',
  'Tractors':                                     'Automobile and Auto Components',
  'Commercial Vehicles':                          'Automobile and Auto Components',
  'Two & Three Wheelers':                         'Automobile and Auto Components',
  'Electric Vehicles':                            'Automobile and Auto Components',
  'Tyres & Rubber Products':                      'Automobile and Auto Components',
  'Auto Ancillaries':                             'Automobile and Auto Components',
  'Bearings':                                     'Automobile and Auto Components',

  // ── Fast Moving Consumer Goods ───────────────────────────────────────────
  'Diversified FMCG':                             'Fast Moving Consumer Goods',
  'Dairy Products':                               'Fast Moving Consumer Goods',
  'Personal Care':                                'Fast Moving Consumer Goods',
  'Edible Oil':                                   'Fast Moving Consumer Goods',
  'Household & Personal Products':                'Fast Moving Consumer Goods',
  'Cigarettes & Tobacco Products':                'Fast Moving Consumer Goods',
  'Breweries & Distilleries':                     'Fast Moving Consumer Goods',
  'Food Processing':                              'Fast Moving Consumer Goods',
  'Sugar':                                        'Fast Moving Consumer Goods',
  'Tea & Coffee':                                 'Fast Moving Consumer Goods',
  'Non-Alcoholic Beverages':                      'Fast Moving Consumer Goods',
  'Agricultural Food & other Products':           'Fast Moving Consumer Goods',
  'Packaged Foods':                               'Fast Moving Consumer Goods',
  'Detergents':                                   'Fast Moving Consumer Goods',

  // ── Capital Goods ─────────────────────────────────────────────────────────
  'Household Appliances':                         'Capital Goods',
  'Consumer Durables':                            'Capital Goods',
  'Heavy Electrical Equipment':                   'Capital Goods',
  'Compressors, Pumps & Diesel Engines':          'Capital Goods',
  'Aerospace & Defense':                          'Capital Goods',
  'Industrial Machinery':                         'Capital Goods',
  'Industrial Capital Goods':                     'Capital Goods',
  'Engineering':                                  'Capital Goods',
  'Electrical Components & Equipments':           'Capital Goods',
  'Cables':                                       'Capital Goods',
  'Transformers & Switchgears':                   'Capital Goods',
  'Electric Equipment':                           'Capital Goods',
  'Defence':                                      'Capital Goods',
  'Industrial Products':                          'Capital Goods',
  'Textile Machinery':                            'Capital Goods',
  'Printing & Packaging':                         'Capital Goods',
  'Process Control & Process Equipment':          'Capital Goods',
  'Other Industrial Products':                    'Capital Goods',
  'Power Equipment':                              'Capital Goods',

  // ── Healthcare ────────────────────────────────────────────────────────────
  'Pharmaceuticals':                              'Healthcare',
  'Pharma - Indian':                              'Healthcare',
  'Pharma - MNC':                                 'Healthcare',
  'Healthcare':                                   'Healthcare',
  'Hospitals & Medical Services':                 'Healthcare',
  'Hospital & Healthcare Services':               'Healthcare',
  'Medical Equipment & Supplies':                 'Healthcare',
  'Medical Devices':                              'Healthcare',
  'Biotechnology':                                'Healthcare',
  'Diagnostics':                                  'Healthcare',
  'Healthcare Services':                          'Healthcare',
  'Drug & Pharmaceutical':                        'Healthcare',

  // ── Consumer Services ─────────────────────────────────────────────────────
  'Hotels & Resorts':                             'Consumer Services',
  'E-Retail/ E-Commerce':                         'Consumer Services',
  'Retail':                                       'Consumer Services',
  'Retailing':                                    'Consumer Services',
  'Quick Service Restaurant':                     'Consumer Services',
  'Restaurant':                                   'Consumer Services',
  'Tourism & Travel':                             'Consumer Services',
  'Travel Agencies':                              'Consumer Services',
  'Airlines':                                     'Consumer Services',
  'Specialty Retail':                             'Consumer Services',
  'Education':                                    'Consumer Services',
  'Leisure & Recreation':                         'Consumer Services',
  'Gems, Jewellery And Watches':                  'Consumer Services',
  'Gems & Jewellery':                             'Consumer Services',

  // ── Metals & Mining ───────────────────────────────────────────────────────
  'Industrial Minerals':                          'Metals & Mining',
  'Iron & Steel/Interm.Products':                 'Metals & Mining',
  'Mining & Mineral products':                    'Metals & Mining',
  'Non Ferrous Metals':                           'Metals & Mining',
  'Trading - Minerals':                           'Metals & Mining',
  'Commodity Trading and Distribution':           'Metals & Mining',
  'Steel':                                        'Metals & Mining',
  'Aluminium':                                    'Metals & Mining',
  'Copper':                                       'Metals & Mining',
  'Zinc':                                         'Metals & Mining',
  'Iron & Steel':                                 'Metals & Mining',
  'Ferro Alloys & Minerals':                      'Metals & Mining',
  'Sponge Iron':                                  'Metals & Mining',
  'Pipes':                                        'Metals & Mining',

  // ── Chemicals ─────────────────────────────────────────────────────────────
  'Plastic Products - Industrial':                'Chemicals',
  'Specialty Chemicals':                          'Chemicals',
  'Agrochemicals':                                'Chemicals',
  'Fertilisers':                                  'Chemicals',
  'Dyes & Pigments':                              'Chemicals',
  'Paints':                                       'Chemicals',
  'Petrochemicals':                               'Chemicals',
  'Chemicals & Petrochemicals':                   'Chemicals',
  'Basic Chemicals':                              'Chemicals',
  'Commodity Chemicals':                          'Chemicals',
  'Plastic Products':                             'Chemicals',
  'Explosives':                                   'Chemicals',
  'Industrial Gases':                             'Chemicals',

  // ── Telecommunication ─────────────────────────────────────────────────────
  'Telecom':                                          'Telecommunication',
  'Telecommunications - Service Provider':            'Telecommunication',
  'Telecommunications - Equipment & Accessories':     'Telecommunication',
  'Telecom Services':                                 'Telecommunication',
  'Broadband & Telecom':                              'Telecommunication',
  'Telecom - Cellular & Fixed line services':         'Telecommunication',

  // ── Power ─────────────────────────────────────────────────────────────────
  'Power Generation':                             'Power',
  'Power Transmission & Distribution':            'Power',
  'Power - Transmission':                         'Power',
  'Power - Generation & Distribution':            'Power',
  'Renewable Energy':                             'Power',
  'Solar Energy':                                 'Power',
  'Wind Energy':                                  'Power',

  // ── Realty ────────────────────────────────────────────────────────────────
  'Residential, Commercial Projects':             'Realty',
  'Real Estate Investment Trusts (REITs)':        'Realty',
  'Real Estate':                                  'Realty',
  'Infrastructure Investment Trusts':             'Realty',

  // ── Construction ──────────────────────────────────────────────────────────
  'Civil Construction':                           'Construction',
  'Infrastructure Developers & Operators':        'Construction',
  'Construction':                                 'Construction',
  'Road & Highway':                               'Construction',
  'Water Supply & Management':                    'Construction',
  'Cement & Cement Products':                     'Construction',
  'Cement':                                       'Construction',

  // ── Media Entertainment & Publication ────────────────────────────────────
  'Media - TV & Broadcasting':                    'Media Entertainment & Publication',
  'Media & Entertainment':                        'Media Entertainment & Publication',
  'Print Media':                                  'Media Entertainment & Publication',
  'Entertainment':                                'Media Entertainment & Publication',
  'OTT Platforms':                                'Media Entertainment & Publication',
  'Film Production & Distribution':               'Media Entertainment & Publication',

  // ── Textiles ──────────────────────────────────────────────────────────────
  'Textiles - Synthetic Blended':                 'Textiles',
  'Textiles - Cotton':                            'Textiles',
  'Textiles':                                     'Textiles',
  'Readymade Garments/ Apparel':                  'Textiles',
  'Spinning':                                     'Textiles',
  'Apparels & Accessories':                       'Textiles',

  // ── Transportation & Logistics ────────────────────────────────────────────
  'Logistics':                                    'Transportation',
  'Courier Services':                             'Transportation',
  'Shipping':                                     'Transportation',
  'Railways':                                     'Transportation',
  'Ports':                                        'Transportation',
  'Road Transport':                               'Transportation',
  'Airport Services':                             'Transportation',
  'Warehousing':                                  'Transportation',
}
